language: python
python:
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - python setup.py install
  - pip install coveralls
# command to run tests
script:
  - python setup.py test && coveralls
notifications:
  slack:
    on_success: never
    on_failure: always
